- hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar HTML al directorio de Apache
      copy:
        src: index.html
        dest: /var/www/html/index.html
